const CreatureEditFormHandles = [
  'creatureEditForm',
  'fieldGroup',
  'label',
  'input',
  'textarea',
  'select',
  'sectionTitle',
  'sectionSubheading',
  'section',
  'grid2',
  'grid3',
  'grid6',
  'actions',
  'submitButton',
  'cancelButton',
  'arrayItem',
  'levelRow',
  'perkItem',
  'removeButton',
  'perkRemoveButton',
  'addButton',
  'headerActions',
  'importMarkdownButton',
  'downloadTemplateButton',
  'spinner',
  'fileInputMarkdown',
] as const;

export default CreatureEditFormHandles;
