const CitizenEditFormHandles = [
  'citizenEditForm',
  'fieldGroup',
  'label',
  'input',
  'textarea',
  'select',
  'sectionTitle',
  'section',
  'grid2',
  'grid3',
  'grid4',
  'grid6',
  'actions',
  'submitButton',
  'cancelButton',
  'arrayItem',
  'removeButton',
  'addButton',
  'headerActions',
  'importMarkdownButton',
  'downloadTemplateButton',
  'spinner',
  'fileInputMarkdown',
  'inlineFields',
  'slotTable',
  'slotTableInput',
  'statTable',
  'statTableRow',
] as const;

export default CitizenEditFormHandles;
