const EvolutionTreeModalHandles = [
  'fullScreenOverlay',
  'fullScreenModal',
  'modalHeader',
  'modalTitle',
  'modalCloseButton',
  'toolbar',
  'toolbarLeft',
  'toolbarCenter',
  'toolbarRight',
  'toolbarBackButton',
  'toolbarAddButton',
  'edgeCanvas',
  'treeNameInput',
  'saveButton',
  'canvas',
  'treeContainer',
  'treeNode',
  'treeNodeContent',
  'treeNodeImage',
  'treeNodeInfo',
  'treeNodeName',
  'treeNodeActions',
  'treeNodeAddBtn',
  'treeNodeRemoveBtn',
  'noTreeMessage',
  'savedTreesList',
  'savedTreeItem',
  'savedTreeItemInfo',
  'savedTreeItemActions',
  'loadTreeBtn',
  'copyBBCodeBtn',
  'deleteTreeBtn',
  'newTreeBtn',
  'sectionTitle',
] as const;

export default EvolutionTreeModalHandles;
